//! Python 3.12 printability from Unicode 15.0 general categories.
//! Generated by ../generate_unicode.py; data license ../LICENSE.unicode.
const BOUNDARIES: &[u8] = include_bytes!("unicode15_printable.bin");
pub fn is_printable(c: char) -> bool {
    let mut low = 0usize;
    let mut high = BOUNDARIES.len() / 4;
    while low < high {
        let middle = (low + high) / 2;
        let bytes = &BOUNDARIES[middle * 4..middle * 4 + 4];
        let point = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
        if point <= c as u32 {
            low = middle + 1;
        } else {
            high = middle;
        }
    }
    low % 2 == 1
}
